coverage:
  precision: 2
  round: down
  range: 80...90

comment:
  layout: 'header, diff, flags, components'

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - '**'
  individual_components:
    - component_id: scss-forge
      name: scss-forge
      paths:
        - packages/scss-forge/**

    - component_id: prismatic
      name: prismatic
      paths:
        - packages/prismatic/**

    - component_id: cli-chroma
      name: cli-chroma
      paths:
        - packages/cli-chroma/**
