name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dedupe:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: De-Dupe dependencies
        run: yarn dedupe --check

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Enforce formatting of project files
        run: yarn format:diff

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test --ci

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: draconic-design/draconic
